apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: g3yhzhko0-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/g3yhzhko0-java-quarkus-gitops